### ISSUE TITLE
Issue about FCD score

### ISSUE THREAD

**Issue by Layne-Huang** [MIRALab-USTC/AI4Sci-MiCaM#1]
Hi,

A low FCD value indicates that the distribution of the real molecules was approximated well by the generated molecules, which is described by the authors of FCD. How do you calculate FCD score which can be opposite to FCD distance?

Thank you.

**Comment by zijiegeng** [comment]
We use the standard scoring functions provided by GuacaMol to score our results. The FCD score is defined as S=exp(-0.2·FCD), and you can find further information about the benchmarking process at https://pubs.acs.org/doi/full/10.1021/acs.jcim.8b00839
