### ISSUE TITLE
Reproduce paper result

### ISSUE THREAD

**Issue by mxc19912008** [MIRALab-USTC/AI4Sci-MiCaM#2]
Great work, curious what is the best way to reproduce the result in paper? Is the hyperparameters in readme good enough? Thanks!

**Comment by zijiegeng** [comment]
Thank you for your interest in our work and sorry for the delay of my response. The hyperparameters in README are sufficient for reproducing the results. You can simply run the commands provided in the README. If you have any questions, please let me know. By the way, I am currently working on improving our code to make it more clear and readable. I would greatly appreciate any suggestions you may have.

**Comment by mxc19912008** [comment]
Thanks for the reply! Does this code also incorporate the conditional generation part, mentioned in 3.2 GOAL DIRECTED GENERATION RESULTS?

**Comment by zijiegeng** [comment]
This part of code is still under improving. I've been busy with another work recently, and after that I will release the code for goal directed task ASAP. Please stay tuned! Thank you a lot.

**Comment by johannaSommer** [comment]
@zijiegeng any updates on this? What would already help is if you could share the hyper parameters for ZINC and Guacamol. The HPs provided in the README seem to be for QM9 and when I try them for ZINC I get a very very low FCD. I have also tried the default hyperparameters in `argparse.py` and they definitely work better, however still not close to what is reported in the paper (currently I get FCD < 0.7 for ZINC).

**Comment by zijiegeng** [comment]
@johannaSommer Hi~The previous hyperparameters were for QM9. I have updated the hyperparameters for ZINC and Guacamol in README. Hope this helps.
