### ISSUE TITLE
Error in SubVocab

### ISSUE THREAD

**Issue by johannaSommer** [MIRALab-USTC/AI4Sci-MiCaM#3]
Dear authors, dear @GengZijie ,

I would like to try to reproduce your results on ZINC and have thus followed all steps provided in the README. Currently, I get an error with the following stack trace:

```
  File "python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/micam/src/model/dataset.py", line 63, in batch_collate
    labels.append(motif_vocab.get_conn_label(motif_idx, conn_idx))
  File "micam/src/model/vocab.py", line 96, in get_conn_label
    return self.vocab_conn_dict[motif_idx][order_idx]
KeyError: 2
```

I have verified that `order_idx` is in fact not in `self.vocab_conn_dict[motif_idx]`. I have tried to debug what the reason for this could be, I assume that the preprocessing of data simply does something different than the collate function does. Is this possibly related to a mismatch in the `utils.get_conn_list` function compared to where I get the error?

I have tried to find a reproducible example for the smiles `CC(C)C[C@H](CNC(=O)[C@H]1CC(=O)Nc2ccccc21)[NH+](C)C`.  The motif that is causing this issue is `*-C-[C@@H](-*)-C-N-C(=O)-C(-*)-*`.  More specifically, I found out that there is in fact a difference in the ranks returned for the motif between preprocessing and during training. 
In `model/utils.py` in the function `get_conn_list ` the input is `[24*]C[C@@H]([25*])CNC(=O)[C@@H]([27*])[29*]`. In `model/vocab.py` the input has the form `*-C-[C@@H](-*)-C-N-C(=O)-C(-*)-*`. Comparing the two I find the following:

```
list(Chem.CanonicalRankAtoms(smiles2mol('[24*]C[C@@H]([25*])CNC(=O)[C@@H]([27*])[29*]'), includeIsotopes=False, breakTies=False))
> [0, 5, 9, 1, 6, 7, 8, 4, 10, 2, 2]
list(Chem.CanonicalRankAtoms(smiles2mol('*-C-[C@@H](-*)-C-N-C(=O)-C(-*)-*'), includeIsotopes=False, breakTies=False))
> [0, 5, 10, 3, 6, 7, 8, 4, 9, 1, 1]
```
Is this intended? Can you give me any hints or pointers to debug this further?

Thanks a lot!

**Comment by zijiegeng** [comment]
Hi,
Thanks for your question. This issue is because we have not considered the chirality of molecules in our implementation. Before running the code on datasets including unconsidered information, like ZINC, we do the following for each smiles:
```
mol = Chem.MolFromSmiles(smiles)
mol = Chem.RemoveAllHs(mol)
for atom in mol.GetAtoms():
    atom.SetChiralTag(Chem.rdchem.ChiralType.CHI_UNSPECIFIED)
for bond in mol.GetBonds():
    bond.SetBondDir(Chem.rdchem.BondDir.NONE)
    bond.SetStereo(Chem.rdchem.BondStereo.STEREONONE)
if mol.GetNumAtoms() > 1:
    smiles = Chem.MolToSmiles(mol)
```
This will transform `CC(C)C[C@H](CNC(=O)[C@H]1CC(=O)Nc2ccccc21)[NH+](C)C` to `CC(C)CC(CNC(=O)C1CC(=O)Nc2ccccc21)[NH+](C)C`. Also, you will find
```
list(Chem.CanonicalRankAtoms(smiles2mol('[24*]CC([25*])CNC(=O)C([27*])[29*]'), includeIsotopes=False, breakTies=False))
> [0, 5, 9, 1, 6, 7, 8, 4, 10, 2, 2]
list(Chem.CanonicalRankAtoms(smiles2mol('*-C-C(-*)-C-N-C(=O)-C(-*)-*'), includeIsotopes=False, breakTies=False))
> [0, 5, 9, 1, 6, 7, 8, 4, 10, 2, 2]
```
I hope this is useful for you.

**Comment by johannaSommer** [comment]
HI @GengZijie  yes I had found out the same thing yesterday as well. At the end it was sufficient to simply preprocess all molecules to remove chiralty. Thanks a lot! :)
